var ollMap = {
  1: [
    "(U) R D R D' R D2' R U' R D2' R U2' R U D' R",
    "R D' R D R D2 R U R D2 R U2 R U' D R",
    "R U D' R U2 R U2 R U R U2 R D R U' R",
    "(U2') R U D' R U2' R D2' R U' R D2' R D' R D R",
    "(U2') R U R D' R U2' R U' R U2' R U2' R U' D R",
    "(U3) R U' D R U2 R D2 R U R D2 R D R D' R",
    "(U) R U' D R U2' R U2' R U' R U2' R D' R U R",
    "(U3) R U' R D R U2 R U R U2 R U2 R U D' R",
    "(U) D R D2 R D' R U R D2 R D R D2 R D2 R",
    "(U') D R D2 R D2 R D R D2 R U R D' R D2 R",
    "(U2') D R U2 R D' R D R D2 R U R D2 R U2 R",
    "(U2) D R U2 R D2 R U R D2 R D R D' R U2 R",
    "D' R D2' R D R U' R D2' R D' R D2' R D2' R",
    "(U2) D' R D2' R D2' R D' R D2' R U' R D R D2' R",
    "(U3) D' R U2' R D R D' R D2' R U' R D2' R U2' R",
    "(U') D' R U2' R D2' R U' R D2' R D' R D R U2' R",
    "(U') R D R U2 R D2 R U D' R D2 R U2' R U R",
    "(U2) R D R U2 R U R U2 R U2 R U D' R U2 R",
    "(U2) R D R U2' R U2 R U D' R U2 R U2 R U R",
    "(U') R D' R U2 R U2' R U' D R U2' R U2' R U' R",
  ],
  2: [
    "(U') D R D' R U R U' D R U R D' R",
    "(U2) D R U' R U R U D' R U R U' R",
    "D' R D R U' R U D' R U' R D R",
    "(U3) D' R U R U' R U' D R U' R U R",
    "R D R U' R U D' R U' R D R D'",
    "(U') R D' R U R U' D R U R D' R D",
    "(U3) R U R U' R U' D R U' R U R D'",
    "(U2) R U' R U R U D' R U R U' R D",
    "D R D R U' R U D' R U' R D R D2'",
    "(U3) D R U R U' R U' D R U' R U R D2'",
    "(U') D' R D' R U R U' D R U R D' R D2",
    "(U2) D' R U' R U R U D' R U R U' R D2",
    "(U') D2 R D' R U R U' D R U R D' R D'",
    "(U2) D2 R U' R U R U D' R U R U' R D'",
    "D2' R D R U' R U D' R U' R D R D",
    "(U3) D2' R U R U' R U' D R U' R U R D",
    "(U2') R U D2 R D' R U D R U' R U' D2' R",
    "(U2') R U D2 R U R U' D' R D R U' D2' R",
    "(U) R U' D2' R D R U' D' R U R U D2 R",
    "(U) R U' D2' R U' R U D R D' R U D2 R",
  ],
  3: [
    "(U) R U D R D' R U D R U' R U' D' R",
    "(U) R U D R U R U' D' R D R U' D' R",
    "R U' D' R D R U' D' R U R U D R",
    "R U' D' R U' R U D R D' R U D R",
    "(U) R U D R D' R U2' D2' R D' R U2 D2 R",
    "(U) R U D R U R U2 D2 R U R U2 D2 R",
    "R U' D' R D R U2 D2 R D R U2' D2' R",
    "R U' D' R U' R U2' D2' R U' R U2' D2' R",
    "R U2 D2 R D' R U D R U' R U2' D2' R",
    "R U2 D2 R D' R U2' D2' R D' R U D R",
    "R U2 D2 R U R U' D' R D R U2' D2' R",
    "R U2 D2 R U R U2 D2 R U R U D R",
    "(U) R U2' D2' R D R U' D' R U R U2 D2 R",
    "(U) R U2' D2' R D R U2 D2 R D R U' D' R",
    "(U) R U2' D2' R U' R U D R D' R U2 D2 R",
    "(U) R U2' D2' R U' R U2' D2' R U' R U' D' R",
    "(U) R D R U D3 R D2 R D2 R U2' R U R",
    "(U) R D R U2' R U2 R U3 D' R U2' R U R",
    "R D' R U' D3 R D2' R D2' R U2 R U' R",
    "R D' R U2 R U2' R U3 D R U2 R U' R",
  ],
  4: [
    "(U) D2 R D2' R U2 R U2' D2 R U2 R D2' R",
    "D2 R U2' R U2 R U2 D2' R U2 R U2' R",
    "D2' R D2 R U2' R U2 D2' R U2' R D2 R",
    "(U) D2' R U2 R U2' R U2' D2 R U2' R U2 R",
    "R D2 R U2' R U2 D2' R U2' R D2 R D2'",
    "(U) R D2' R U2 R U2' D2 R U2 R D2' R D2",
    "(U) R U2 R U2' R U2' D2 R U2' R U2 R D2'",
    "R U2' R U2 R U2 D2' R U2 R U2' R D2",
    "(U) D R D2' R U2 R U2' D2 R U2 R D2' R D",
    "D R U2' R U2 R U2 D2' R U2 R U2' R D",
    "D' R D2 R U2' R U2 D2' R U2' R D2 R D'",
    "(U) D' R U2 R U2' R U2' D2 R U2' R U2 R D'",
    "(U) D2 R D2' R U2 R U D' R D2 R U3 D R",
    "D2 R U D3 R D2 R U' D R U2 R U2' R",
    "D2 R U2' R U2 R U' D R D2 R U D3 R",
    "(U) D2 R U3 D R D2 R U D' R U2 R D2' R",
    "D2' R D2 R U2' R U' D R D2' R U3 D' R",
    "(U) D2' R U' D3 R D2' R U D' R U2' R U2 R",
    "(U) D2' R U2 R U2' R U D' R D2' R U' D3 R",
    "D2' R U3 D' R D2' R U' D R U2' R D2 R",
  ],
  5: [
    "(U2') R D2' R D R D' R U R U' D2 R",
    "(U) R U2' R D R U' R U R U2 D' R",
    "(U3) R U D' R D R D' R U R U2' D R",
    "R U' D R D R U' R U R U D2' R",
    "(U) R U D3 R U R U' R D R U' D2 R",
    "R U2 D2' R U R U' R D R U2' D R",
    "(U3) R U2' D2 R U R D' R D R U D2' R",
    "(U2') R U3 D R U R D' R D R U2 D' R",
    "(U') R U' R U2' R U2' R U2 R U2' R U R",
    "(U2') R D2' R D R U3 D2 R D R U2 D' R",
    "(U) R U2' R D R U2 D3 R D R U' D2 R",
    "(U2') D R D2' R D R D' R U R U' D2 R D'",
    "(U) D R U2' R D R U' R U R U2 D' R D'",
    "(U2') D' R D2' R D R D' R U R U' D2 R D",
    "(U) D' R U2' R D R U' R U R U2 D' R D",
    "(U2') R D R U R U2 D' R D R D' R U2' R",
    "(U) R U2' R D R U' R U R U' D' R U3 R",
    "(U) R U3 R D R U R D' R D R U2 D' R",
    "(U2') R U3 R U R D R U' R U R U2 D' R",
    "(U2') D2 R D2' R D R D' R U R U' D2 R D2'",
  ],
  6: [
    "(U') R U' D2 R U R D' R D R D2' R",
    "(U2) R U2 D' R U R U' R D R U2' R",
    "(U3) R U D2' R U R U' R D R U' D R",
    "R U2' D R U R D' R D R U D' R",
    "R U D2' R D R D' R U R U2' D2 R",
    "(U2) R U' D2 R D R U' R U R U D3 R",
    "(U') R U2 D' R D R D' R U R U3 D R",
    "(U3) R U2' D R D R U' R U R U2 D2' R",
    "(U) R U R U2' R U2 R U2' R U2' R U' R",
    "(U2) R U' D2 R D R U2 D3 R D R U2' R",
    "(U') R U2 D' R D R U3 D2 R D R D2' R",
    "(U') D R U' D2 R U R D' R D R D2' R D'",
    "(U2) D R U2 D' R U R U' R D R U2' R D'",
    "(U') D' R U' D2 R U R D' R D R D2' R D",
    "(U2) D' R U2 D' R U R U' R D R U2' R D",
    "(U) R U2' R D' R D R U2 D' R U R D R",
    "(U') R U2 D' R D R D' R U R D R U3 R",
    "(U2) R U2 D' R U R U' R D R U R U3 R",
    "(U') R U3 R U' D' R U R U' R D R U2' R",
    "(U') D2 R U' D2 R U R D' R D R D2' R D2'",
  ],
  7: [
    "(U2) R D R D' R D R U' R U D' R",
    "R U D' R U' R D R D' R D R",
    "(U') R U R D' R U R U' R U' D R",
    "(U3) R U' D R U' R U R D' R U R",
    "(U2) R D R D' R U3 D2' R D' R U2' D2 R",
    "(U') R U R D' R U2' D3 R D' R U2 D2' R",
    "(U3) R U2 D2' R D' R U R U' R U2' D3 R",
    "(U3) R U2 D2' R D' R U2' D3 R D' R U R",
    "R U2' D2 R D' R D R U' R U3 D2' R",
    "R U2' D2 R D' R U3 D2' R D' R D R",
    "(U') R U2' D3 R U' R U R D' R U2 D2' R",
    "(U2) R U3 D2' R U' R D R D' R U2' D2 R",
    "(U2) D R D R D' R D R U' R U D' R D'",
    "D R U D' R U' R D R D' R D R D'",
    "(U') D R U R D' R U R U' R U' D R D'",
    "(U3) D R U' D R U' R U R D' R U R D'",
    "(U2) D' R D R D' R D R U' R U D' R D",
    "D' R U D' R U' R D R D' R D R D",
    "(U') D' R U R D' R U R U' R U' D R D",
    "(U3) D' R U' D R U' R U R D' R U R D",
  ],
  8: [
    "(U) R U D' R U R U2 R U R U2 R U2 R D R",
    "(U) R U D' R U' R D2' R U' R D2' R U2' R U' R",
    "(U2') R U' D R U R D2 R U R D2 R U2 R U R",
    "(U2') R U' D R U' R U2' R U' R U2' R U2' R D' R",
  ],
  9: [
    "R U R U2' R U' R U' R U2' R U2 R",
    "(U2') R U' R U2 R U R U R U2 R U2' R",
    "(U2') R U2 R U2' R U' R U' R U2' R U R",
    "R U2' R U2 R U R U R U2 R U' R",
    "D R U R U2' R U' R U' R U2' R U2 R D'",
    "(U2') D R U' R U2 R U R U R U2 R U2' R D'",
    "(U2') D R U2 R U2' R U' R U' R U2' R U R D'",
    "D R U2' R U2 R U R U R U2 R U' R D'",
    "D' R U R U2' R U' R U' R U2' R U2 R D",
    "(U2') D' R U' R U2 R U R U R U2 R U2' R D",
    "(U2') D' R U2 R U2' R U' R U' R U2' R U R D",
    "D' R U2' R U2 R U R U R U2 R U' R D",
    "(U3) R D R U2' R D' R U' R D R U3 R D' R",
    "(U3) R D R U3 R D' R U R D R U2 R D' R",
    "(U) R D' R U2 R D R U R D' R U3 R D R",
    "(U) R D' R U3 R D R U' R D' R U2' R D R",
    "R U R U2' R U' R U' R U R U3 R U' R",
    "R U R U3 R U' R U R U R U2 R U' R",
    "(U2') R U' R U2 R U R U R U' R U3 R U R",
    "(U2') R U' R U3 R U R U' R U' R U2' R U R",
  ],
  10: [
    "(U2') R D R U2 R U2 R U R U2 R U R U D' R",
    "(U3) R D' R U2' R U2' R U' R U2' R U' R U' D R",
    "(U) R U R U2 R D2 R U R D2 R U R U' D R",
    "R U' R U2' R D2' R U' R D2' R U' R U D' R",
  ],
  11: [
    "R D R U R D2 R U R D2 R",
    "(U') R D' R U' R D2' R U' R D2' R",
    "(U3) R U R U R U2 R U R U2 R",
    "(U2) R U' R U' R U2' R U' R U2' R",
    "D R D R U R D2 R U R D2 R D'",
    "(U') D R D' R U' R D2' R U' R D2' R D'",
    "(U3) D R U R U R U2 R U R U2 R D'",
    "(U2) D R U' R U' R U2' R U' R U2' R D'",
    "D' R D R U R D2 R U R D2 R D",
    "(U') D' R D' R U' R D2' R U' R D2' R D",
    "(U3) D' R U R U R U2 R U R U2 R D",
    "(U2) D' R U' R U' R U2' R U' R U2' R D",
    "(U3) R U R U R U2 R U R U' R U3 R",
    "(U2') R U R U' R U' R U2' R U2' R U2 R",
    "(U) R U' R U R U R U2 R U2 R U2' R",
    "(U2) R U' R U' R U2' R U' R U R U3 R",
    "D2 R D R U R D2 R U R D2 R D2'",
    "(U') D2 R D' R U' R D2' R U' R D2' R D2'",
    "(U3) D2 R U R U R U2 R U R U2 R D2'",
    "(U2) D2 R U' R U' R U2' R U' R U2' R D2'",
  ],
  12: [
    "(U2) R U D2' R U' R D R D' R D2 R",
    "(U') R U2' D R U' R U R D' R U2 R",
    "(U2') R U' D2 R U' R U R D' R U D' R",
    "(U) R U2 D' R U' R D R D' R U' D R",
    "(U') R U D2' R D' R U R U' R U' D3 R",
    "(U) R U' D2 R D' R D R U' R U2 D2' R",
    "(U2') R U2 D' R D' R U R U' R U2' D2 R",
    "(U2) R U2' D R D' R D R U' R U3 D' R",
    "R U' R U2 R U2' R U2 R U2 R U R",
    "(U') R U D2' R D' R U2' D3 R D' R U2 R",
    "(U2) R U2' D R D' R U3 D2' R D' R D2 R",
    "(U2) D R U D2' R U' R D R D' R D2 R D'",
    "(U') D R U2' D R U' R U R D' R U2 R D'",
    "(U2) D' R U D2' R U' R D R D' R D2 R D",
    "(U') D' R U2' D R U' R U R D' R U2 R D",
    "R U2 R D R D' R U2' D R U' R D' R",
    "(U2) R U2' D R D' R D R U' R D' R U3 R",
    "(U') R U2' D R U' R U R D' R U' R U3 R",
    "(U2) R U3 R U D R U' R U R D' R U2 R",
    "(U2) D2 R U D2' R U' R D R D' R D2 R D2'",
  ],
  13: [
    "(U3) R D2 R D' R D R U' R U D2' R",
    "R U2 R D' R U R U' R U2' D R",
    "(U) R U D' R D' R U R U' R U' D2 R",
    "(U2') R U' D R D' R D R U' R U2 D' R",
    "R U' D3 R U' R U R D' R U D2' R",
    "(U2') R U2 D2' R U' R D R D' R U' D2 R",
    "(U) R U2' D2 R U' R U R D' R U2 D' R",
    "(U3) R U3 D' R U' R D R D' R U2' D R",
    "(U2) R U R U2 R U2 R U2' R U2 R U' R",
    "(U3) R D2 R D' R U3 D2' R D' R U2' D R",
    "R U2 R D' R U2' D3 R D' R U D2' R",
    "(U3) D R D2 R D' R D R U' R U D2' R D'",
    "D R U2 R D' R U R U' R U2' D R D'",
    "(U3) D' R D2 R D' R D R U' R U D2' R D",
    "D' R U2 R D' R U R U' R U2' D R D",
    "(U3) R D' R U' R U2' D R D' R D R U2 R",
    "R U2 R D' R U R U' R U D R U3 R",
    "R U3 R D' R U' R D R D' R U2' D R",
    "(U3) R U3 R U' R D' R U R U' R U2' D R",
    "(U3) D2 R D2 R D' R D R U' R U D2' R D2'",
  ],
  14: [
    "(U2) R U D2' R U' D2 R U R U D2' R U' D2 R",
    "R U D2' R U' D2 R U' R U D2' R U' D2 R",
    "(U2) R U D2' R U2 D' R D R U2' D R U' D2 R",
    "R U D2' R U2 D' R D' R U2' D R U' D2 R",
    "R U' D2 R U D2' R U R U' D2 R U D2' R",
    "(U) R U' D2 R U D2' R U' R U' D2 R U D2' R",
    "R U' D2 R U2' D R D R U2 D' R U D2' R",
    "(U) R U' D2 R U2' D R D' R U2 D' R U D2' R",
    "R U2 D' R U D2' R D R U' D2 R U2' D R",
    "(U) R U2 D' R U D2' R D' R U' D2 R U2' D R",
    "R U2 D' R U2' D R U R U2 D' R U2' D R",
    "(U) R U2 D' R U2' D R U' R U2 D' R U2' D R",
    "(U2) R U2' D R U' D2 R D R U D2' R U2 D' R",
    "R U2' D R U' D2 R D' R U D2' R U2 D' R",
    "(U2) R U2' D R U2 D' R U R U2' D R U2 D' R",
    "R U2' D R U2 D' R U' R U2' D R U2 D' R",
    "R U D2' R U' D2 R U2 R U D2' R U' D2 R",
    "(U2) R U D2' R U' D2 R U2' R U D2' R U' D2 R",
    "R U D2' R U2 D' R D2 R U2' D R U' D2 R",
    "(U2) R U D2' R U2 D' R D2' R U2' D R U' D2 R",
  ],
  15: [
    "(U2) R D2 R U R D2 R U R D R",
    "(U') R D2' R U' R D2' R U' R D' R",
    "(U') R U2 R U R U2 R U R U R",
    "(U2) R U2' R U' R U2' R U' R U' R",
    "(U2) D R D2 R U R D2 R U R D R D'",
    "(U') D R D2' R U' R D2' R U' R D' R D'",
    "(U') D R U2 R U R U2 R U R U R D'",
    "(U2) D R U2' R U' R U2' R U' R U' R D'",
    "(U2) D' R D2 R U R D2 R U R D R D",
    "(U') D' R D2' R U' R D2' R U' R D' R D",
    "(U') D' R U2 R U R U2 R U R U R D",
    "(U2) D' R U2' R U' R U2' R U' R U' R D",
    "(U') R U2 R U2' R U2' R U' R U' R U R",
    "(U2) R U2' R U2 R U2 R U R U R U' R",
    "(U') R U3 R U R U' R U2' R U' R U' R",
    "(U2) R U3 R U' R U R U2 R U R U R",
    "(U2) D2 R D2 R U R D2 R U R D R D2'",
    "(U') D2 R D2' R U' R D2' R U' R D' R D2'",
    "(U') D2 R U2 R U R U2 R U R U R D2'",
    "(U2) D2 R U2' R U' R U2' R U' R U' R D2'",
  ],
  16: [
    "(U') R D' R D R D' R U R U' D R",
    "(U2') R U D' R U R U' R D R U' R",
    "(U) R U' D R U R D' R D R D' R",
    "(U2) R U' R D R U' R U R U D' R",
    "(U') R D' R D R U3 D2 R D R U2 D2' R",
    "(U2) R U' R D R U2 D3 R D R U2' D2 R",
    "(U) R U2 D2' R D R D' R U R U3 D2 R",
    "(U) R U2 D2' R D R U3 D2 R D R D' R",
    "(U2) R U2 D3 R U R U' R D R U2' D2 R",
    "(U2') R U2' D2 R D R U' R U R U2 D3 R",
    "(U2') R U2' D2 R D R U2 D3 R D R U' R",
    "(U') R U3 D2 R U R D' R D R U2 D2' R",
    "(U') D R D' R D R D' R U R U' D R D'",
    "(U2') D R U D' R U R U' R D R U' R D'",
    "(U) D R U' D R U R D' R D R D' R D'",
    "(U2) D R U' R D R U' R U R U D' R D'",
    "(U') D' R D' R D R D' R U R U' D R D",
    "(U2') D' R U D' R U R U' R D R U' R D",
    "(U) D' R U' D R U R D' R D R D' R D",
    "(U2) D' R U' R D R U' R U R U D' R D",
  ],
  17: [
    "(U2') D2 R U R U' R U' R D2' R U2 R U2' R",
    "D2 R U2' R U2 R D2' R U' R U' R U R",
    "(U) D2' R U' R U R U R D2 R U2' R U2 R",
    "(U') D2' R U2 R U2' R D2 R U R U R U' R",
    "(U) R D R U' R U R D2 R D2' R U' D3 R",
    "(U) R D R U' R U R U3 D' R U2' R U2 R",
    "(U2') R D' R U R U' R D2' R D2 R U D3 R",
    "(U2') R D' R U R U' R U3 D R U2 R U2' R",
    "(U2') R D2 R U D3 R D2 R D R U' R U R",
    "(U) R D2' R U' D3 R D2' R D' R U R U' R",
    "(U2') R U D3 R D2 R D2' R U' R U R D' R",
    "(U2') R U R U' R D R D2 R U D3 R D2 R",
    "(U2') R U R U' R U' R D2' R U2 R U2' R D2",
    "(U) R U' D3 R D2' R D2 R U R U' R D R",
    "(U) R U' R U R D' R D2' R U' D3 R D2' R",
    "(U) R U' R U R U R D2 R U2' R U2 R D2'",
    "(U') R U2 R U2' R D2 R U R U R U' R D2'",
    "(U) R U2 R U2' R U3 D' R U R U' R D R",
    "R U2' R U2 R D2' R U' R U' R U R D2",
    "(U2') R U2' R U2 R U3 D R U' R U R D' R",
  ],
  18: [
    "(U2') R D2 R D2 R U2 R U2' R U2 D2' R D2' R",
    "R D2 R U2' D2 R U2 R U2' R D2' R D2' R",
    "R D2' R D2' R U2' R U2 R U2' D2 R D2 R",
    "(U2') R D2' R U2 D2' R U2' R U2 R D2 R D2 R",
    "R U2 D2' R U2 R U2' R D2 R U2 R U2 R",
    "(U2') R U2 R D2 R U2' R U2 R U2 D2' R U2' R",
    "(U2) R U2 R U2 R D2 R U2' R U2 R U2 D2' R",
    "(U2) R U2 R U2' D2 R U2' R U2 R D2' R U2' R",
    "(U2') R U2' D2 R U2' R U2 R D2' R U2' R U2' R",
    "R U2' R D2' R U2 R U2' R U2' D2 R U2 R",
    "(U2) R U2' R U2 D2' R U2 R U2' R D2 R U2 R",
    "(U2) R U2' R U2' R D2' R U2 R U2' R U2' D2 R",
    "(U') R U D' R U2 R U2 R U2' R U2 R U' D R",
    "(U3) R U D' R U2' R U2 R U2' R U2' R U' D R",
    "(U) R U' D R U2 R U2' R U2 R U2 R U D' R",
    "(U') R U' D R U2' R U2' R U2 R U2' R U D' R",
    "(U2') D R D2 R D2 R D2' R D2 R U D' R D2 R",
    "(U') D R D2 R U D' R D2 R D2' R D2 R D2 R",
    "(U2') D R U D' R D2' R D2' R D2 R U2 R U2 R",
    "(U2') D R U2 R D2 R D2 R D2' R U D' R U2 R",
  ],
  19: [
    "(U2) R U R U2 R U' R U2 R U2' R U2 R",
    "(U') R U2' R U2 R U2' R U R U2' R U' R",
    "(U) R D R U R D' R U R D R U2' R D' R",
    "(U3) R D R U' R D' R U' R D R U2 R D' R",
    "(U) R D R U2 R D' R U' R D R U' R D' R",
    "(U3) R D R U2' R D' R U R D R U R D' R",
    "(U2') R U R U R U' R U R U R U2' R U' R",
    "R U R U' R U' R U' R U R U2 R U' R",
    "(U2') R U R U2 R U' R U' R U R U' R U' R",
    "R U R U2' R U' R U R U R U R U' R",
    "(U2) R D R U R D' R U2' R D R U2 R D' R",
    "(U2) R D R U' R D' R U2 R D R U2' R D' R",
    "(U) R D R U2 R D' R U2' R D R U R D' R",
    "(U3) R D R U2' R D' R U2 R D R U' R D' R",
    "(U') R U R U R U' R U2' R U R U2 R U' R",
    "(U') R U R U' R U' R U2 R U R U2' R U' R",
    "(U2') R U R U2 R U' R U2' R U R U R U' R",
    "R U R U2' R U' R U2 R U R U' R U' R",
    "(U2) D R U R U2 R U' R U2 R U2' R U2 R D'",
    "(U') D R U2' R U2 R U2' R U R U2' R U' R D'",
  ],
  20: [
    "(U) D R D2 R D2 R U' D R D2 R D2 R",
    "D R U2 R D2 R U D' R D2 R U2 R",
    "D' R D2' R D2' R U D' R D2' R D2' R",
    "(U) D' R U2' R D2' R U' D R D2' R U2' R",
    "(U) R D2 R D2 R U' D R D2 R D2 R D",
    "R D2' R D2' R U D' R D2' R D2' R D'",
    "R U2 R D2 R U D' R D2 R U2 R D",
    "(U) R U2' R D2' R U' D R D2' R U2' R D'",
    "D R D2' R D2' R U D' R D2' R D2' R D2'",
    "(U) D R U2' R D2' R U' D R D2' R U2' R D2'",
    "(U) D' R D2 R D2 R U' D R D2 R D2 R D2",
    "D' R U2 R D2 R U D' R D2 R U2 R D2",
    "(U) D2 R D2 R D2 R U' D R D2 R D2 R D'",
    "D2 R U2 R D2 R U D' R D2 R U2 R D'",
    "D2' R D2' R D2' R U D' R D2' R D2' R D",
    "(U) D2' R U2' R D2' R U' D R D2' R U2' R D",
    "D2 R D2' R D2' R U D' R U3 D R U2' R",
    "D2 R D2' R U3 D R U' D R D2' R U2' R",
    "(U) D2 R U2' R D2' R U' D R U3 D R D2' R",
    "(U) D2 R U2' R U3 D R U D' R D2' R D2' R",
  ],
  21: [
    "(U) R U' R U2' R U R U2' R U2 R U2' R",
    "(U2') R U2 R U2' R U2 R U' R U2 R U R",
    "R D' R U R D R U R D' R U2' R D R",
    "(U2) R D' R U' R D R U' R D' R U2 R D R",
    "R D' R U2 R D R U' R D' R U' R D R",
    "(U2) R D' R U2' R D R U R D' R U R D R",
    "(U3) R U' R U R U R U R U' R U2' R U R",
    "(U') R U' R U' R U R U' R U' R U2 R U R",
    "(U3) R U' R U2 R U R U' R U' R U' R U R",
    "(U') R U' R U2' R U R U R U' R U R U R",
    "(U) R D' R U R D R U2' R D' R U2 R D R",
    "(U) R D' R U' R D R U2 R D' R U2' R D R",
    "R D' R U2 R D R U2' R D' R U R D R",
    "(U2) R D' R U2' R D R U2 R D' R U' R D R",
    "(U2') R U' R U R U R U2' R U' R U2 R U R",
    "(U2') R U' R U' R U R U2 R U' R U2' R U R",
    "(U3) R U' R U2 R U R U2' R U' R U R U R",
    "(U') R U' R U2' R U R U2 R U' R U' R U R",
    "(U) D R U' R U2' R U R U2' R U2 R U2' R D'",
    "(U2') D R U2 R U2' R U2 R U' R U2 R U R D'",
  ],
  22: [
    "(U2) R D2 R U R D' R U2' R D R U2 R D2' R",
    "(U3) R D2 R U2' R D' R U2 R D R U' R D2' R",
    "(U) R D2' R U' R D R U2 R D' R U2' R D2 R",
    "R D2' R U2 R D R U2' R D' R U R D2 R",
    "R U R U2 R U' D' R U2 R U2' R U2 D R",
    "(U3) R U' R U2' R U D R U2' R U2 R U2' D' R",
    "R U2 D R U2' R U2 R U' D' R U2 R U R",
    "(U') R U2 R U R U' R U2' R U R U2 R U2' R",
    "R U2 R U2' R U' R U2 R U R U' R U2' R",
    "(U3) R U2' D' R U2 R U2' R U D R U2' R U' R",
    "(U2') R U2' R U' R U R U2 R U' R U2' R U2 R",
    "(U3) R U2' R U2 R U R U2' R U' R U R U2 R",
    "R U D2 R D2 R U D R U' D3 R U' D2' R",
    "R U D2 R U D3 R U' D' R D2' R U' D2' R",
    "R U D2 R U2' R U' D' R U3 D R U' D2' R",
    "R U D2 R U3 D' R U D R U2 R U' D2' R",
    "(U3) R U' D2' R D2' R U' D' R U D3 R U D2 R",
    "(U3) R U' D2' R U' D3 R U D R D2 R U D2 R",
    "(U3) R U' D2' R U2 R U D R U3 D' R U D2 R",
    "(U3) R U' D2' R U3 D R U' D' R U2' R U D2 R",
  ],
  23: [
    "R U D R U D' R U D R U2' R U' D' R",
    "R U D R U2 R U' D' R U' D R U' D' R",
    "R U' D' R U' D R U' D' R U2 R U D R",
    "R U' D' R U2' R U D R U D' R U D R",
    "D R D2 R U D' R U D' R U D' R D2 R",
    "D R U' D' R U2 R U D R U2' R U' D' R",
    "D R U' D' R U2' R U D R U2 R U' D' R",
    "D R U2 R U D' R U' D R U D' R U2 R",
    "D' R D2' R U' D R U' D R U' D R D2' R",
    "D' R U D R U2 R U' D' R U2' R U D R",
    "D' R U D R U2' R U' D' R U2 R U D R",
    "D' R U2' R U' D R U D' R U' D R U2' R",
    "R D2 R U D' R U D' R U D' R D2 R D",
    "R D2' R U' D R U' D R U' D R D2' R D'",
    "R U D R U2 R U' D' R U2' R U D R D'",
    "R U D R U2' R U' D' R U2 R U D R D'",
    "R U' D' R U2 R U D R U2' R U' D' R D",
    "R U' D' R U2' R U D R U2 R U' D' R D",
    "R U2 R U D' R U' D R U D' R U2 R D",
    "R U2' R U' D R U D' R U' D R U2' R D'",
  ]
};
